defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.6.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - npm-deps-{{ checksum "package.json" }}
        - npm-deps-
    - run:
        name: Run npm ci
        command: npm ci
    - run:
        name: Run build
        command: npm run build
    - save_cache:
        paths:
          - node_modules
        key: npm-deps-{{ checksum "package.json" }}
    - persist_to_workspace:
        root: ~/repo
        paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  ci:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
